### PR TITLE
Fix memory leak in `loki.process` on config update

### LINKED ISSUE #311: Goroutine/Memory leak in Loki
### What's wrong?

We're getting constant memory leaks in our GA flow deployment. After attaching profiling, it looks like there is a goroutine leak in Loki processing, due to which the CRI config also leaks memory. We're getting Kubernetes pod logs inside a cluster. We've had larger leakage issues before - it turned out that it was due to trying to tail logs that didn't exist - scoping the Kubernetes discovery to the current node helped. We've noticed that if the leaks still occur, they happen mostly on dev environments - I suspect there might be a lack of cleanup of the targets once pods are deleted.

Although this might be a configuration error that still resolves log files that don't exist, it'd be great if GA handled them gracefully.

Screenshot 2023-11-03 at 12 44 39

[goroutine-pprof.pb.gz](https://github.com/grafana/agent/files/13249721/goroutine-pprof.pb.gz)
[inuse_space-pprof.pb.gz](https://github.com/grafana/agent/files/13249725/inuse_space-pprof.pb.gz)

### Steps to reproduce

Apply the below config in a dynamic k8s environment and observe. It could take about 24h for the memory to accumulate significantly.

### System information

GKE, amd64

### Software version

0.37.2

### Configuration

```text
// grafana-agent-flow.river
logging {
	level  = "warn"
	format = "logfmt"
}

module.file "env" {
	filename = "/etc/agent/env.river"
}

module.file "all_pods" {
	filename = "/etc/agent/all-pods.river"
}

module.file "loki" {
	filename = "/etc/agent/loki.river"

	arguments {
		project             = module.file.env.exports.project
		project_id          = module.file.env.exports.project_id
		cluster             = module.file.env.exports.cluster
		all_pods_targets    = module.file.all_pods.exports.targets
		gcplog_subscription = module.file.env.exports.gcplog_subscription
	}
}

module.file "tempo" {
	filename = "/etc/agent/tempo.river"

	arguments {
		project = module.file.env.exports.project
		cluster = module.file.env.exports.cluster
	}
}

module.file "pyroscope" {
	filename = "/etc/agent/pyroscope.river"

	arguments {
		project = module.file.env.exports.project
		cluster = module.file.env.exports.cluster
	}
}

// all-pods.river
discovery.kubernetes "this" {
	role = "pod"

	selectors {
		role  = "pod"
		field = "spec.nodeName=" + env("KUBE_NODE_NAME")
	}
}

module.file "relabel" {
	filename = "/etc/agent/relabel.river"

	arguments {
		targets = discovery.kubernetes.this.targets
	}
}

export "targets" {
	value = module.file.relabel.exports.output
}

// loki.river
argument "project" { }

argument "project_id" { }

argument "cluster" { }

argument "all_pods_targets" { }

argument "gcplog_subscription" { }

loki.write "default" {
	endpoint {
		url = "REDACTED"
	}

	external_labels = {
		project = argument.project.value,
		cluster = argument.cluster.value,
	}
}

loki.process "this" {
	forward_to = [loki.write.default.receiver]

	stage.drop {
		older_than          = "3h"
		drop_counter_reason = "too old"
	}
}

module.file "pods_log" {
	filename = "/etc/agent/pods-log.river"

	arguments {
		targets   = argument.all_pods_targets.value
		receivers = [loki.process.this.receiver]
	}
}

module.file "kubernetes_events_log" {
	filename = "/etc/agent/kubernetes-events-log.river"

	arguments {
		cluster   = argument.cluster.value
		receivers = [loki.process.this.receiver]
	}
}

module.file "gcp_log" {
	filename = "/etc/agent/gcp-log.river"

	arguments {
		project      = argument.project.value
		project_id   = argument.project_id.value
		subscription = argument.gcplog_subscription.value
		receivers    = [loki.process.this.receiver]
	}
}

// pods-log.river
argument "targets" { }

argument "receivers" { }

discovery.relabel "this" {
	targets = argument.targets.value

	rule {
		source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
		target_label  = "__path__"
		separator     = "/"
		replacement   = "/var/log/pods/*$1/*.log"
	}

	rule {
		source_labels = [
			"__meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash",
			"__meta_kubernetes_pod_annotation_kubernetes_io_config_hash",
			"__meta_kubernetes_pod_container_name",
		]
		regex        = "true/(.*)"
		target_label = "__path__"
		separator    = "/"
		replacement  = "/var/log/pods/*$1/*.log"
	}
}

local.file_match "logs" {
	path_targets = discovery.relabel.this.output
}

loki.source.file "this" {
	targets    = local.file_match.logs.targets
	forward_to = [loki.process.this.receiver]
}

loki.process "this" {
	forward_to = argument.receivers.value

	stage.cri { }

	// log level detection
	stage.match {
		selector = "{kind=\"node-js\"}"

		stage.json {
			expressions = {level = "", type = ""}
		}

		stage.labels {
			values = {level = "", type = ""}
		}

		stage.template {
			source   = "level"
			template = "{{ if eq .Value \"10\" }}{{ Replace .Value \"10\" \"trace\" -1 }}{{ else if eq .Value \"20\" }}{{ Replace .Value \"20\" \"debug\" -1 }}{{ else if eq .Value \"30\" }}{{ Replace .Value \"30\" \"info\" -1 }}{{ else if eq .Value \"40\" }}{{ Replace .Value \"40\" \"warn\" -1 }}{{ else if eq .Value \"50\" }}{{ Replace .Value \"50\" \"error\" -1 }}{{ else if eq .Value \"60\" }}{{ Replace .Value \"60\" \"fatal\" -1 }}{{ else }}{{ .Value }}{{ end }}"
		}

		stage.labels {
			values = {level = ""}
		}
	}
}
```

### Logs

_No response_

### PR DESCRIPTION
**Pull request by ptodev**
#### PR Description

A goroutine wasn't being stopped in `Update`, which resulted in a memory leak.

#### Which issue(s) this PR fixes

Fixes #311

#### PR Checklist

- [x] CHANGELOG.md updated
- [ ] Documentation added
- [x] Tests updated
- [ ] Config converters updated

### CODE REVIEW

File: internal/component/loki/process/process.go [hunk 1]
```diff
@@ -138,8 +137,9 @@ func (c *Component) Update(args component.Arguments) error {
 		if err != nil {
 			return err
 		}
-		c.entryHandler = loki.NewEntryHandler(c.processOut, func() { pipeline.Cleanup() })
-		c.processIn = pipeline.Wrap(c.entryHandler).Chan()
+		entryHandler := loki.NewEntryHandler(c.processOut, func() { pipeline.Cleanup() })
+		c.entryHandler = pipeline.Wrap(entryHandler)
```
Comment (thampiotr) [inline internal/component/loki/process/process.go:141]: I see that pipeline.Wrap starts goroutines and it seems like we were not calling `Stop()` on the wrapped pipeline before. LMK if I'm missing something here.

File: internal/component/loki/process/process.go [hunk 2]
```diff
@@ -101,7 +101,6 @@ func (c *Component) Run(ctx context.Context) error {
 		if c.entryHandler != nil {
 			c.entryHandler.Stop()
 		}
-		close(c.processIn)
```
Comment (thampiotr) [inline internal/component/loki/process/process.go:104]: We're removing this just because it could lead to writes to a closed channel?

File: internal/component/loki/process/process_test.go [hunk 3]
```diff
@@ -401,6 +407,8 @@ stage.static_labels {
 }
 
 func TestDeadlockWithFrequentUpdates(t *testing.T) {
```
Comment (thampiotr) [inline internal/component/loki/process/process_test.go:409]: This test became a bit harder to follow now. Maybe we could simplify it somehow?

**Review by thampiotr — APPROVED** [review]
One nit and question, but otherwise LGTM.

File: internal/component/loki/process/process.go (hunk 2 above)
Comment (ptodev) [reply internal/component/loki/process/process.go:104]: No, it's because `c.entryHandler.Stop()` will now close `c.processIn` appropriately. If we still have `close(c.processIn)`, we will actually get a panic in the unit tests:
```
panic: close of closed channel

goroutine 90 [running]:
github.com/grafana/alloy/internal/component/loki/process.(*Component).Run.func1()
        /Users/paulintodev/Documents/GitHub/alloy-1/internal/component/loki/process/process.go:104 +0x98
github.com/grafana/alloy/internal/component/loki/process.(*Component).Run(0x14000c970e0, {0x102ff1578, 0x140005f0a00})
        /Users/paulintodev/Documents/GitHub/alloy-1/internal/component/loki/process/process.go:113 +0x158
created by github.com/grafana/alloy/internal/component/loki/process.TestJSONLabelsStage in goroutine 82
        /Users/paulintodev/Documents/GitHub/alloy-1/internal/component/loki/process/process_test.go:99 +0x490
FAIL    github.com/grafana/alloy/internal/component/loki/process        0.772s
FAIL
```

File: internal/component/loki/process/process.go (hunk 1 above)
Comment (ptodev) [reply internal/component/loki/process/process.go:141]: Yes, we didn't call `Stop()` for the new entry handler (the one coming from `Wrap()`) but rather on the first entry handler. For everything to close properly, I think the "outmost" entry handler must be closed.

File: internal/component/loki/process/process_test.go (hunk 3 above)
Comment (ptodev) [reply internal/component/loki/process/process_test.go]: No worries, I refactored it. I think it looks better now?

**Comment by aglees** [comment]
Any ideas on the failing test?

**Review by thampiotr — APPROVED** [review]
