### PR TITLE
[prometheus.exporter.windows] Fix default values

### LINKED ISSUE #1845: Some missed metrics with Alloy 1.4.x on Windows Server 2022 Datacenter
### What's wrong?

Alloy does not export windows metrics, at least for

- net
- logical_disk
- phisical_disk

while no errors or timeout are reported:

```
# HELP windows_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, goversion from which windows_exporter was built, and the goos and goarch for the build.
# TYPE windows_exporter_build_info gauge
windows_exporter_build_info{branch="HEAD",goarch="amd64",goos="windows",goversion="go1.22.7",revision="f59e491e5",tags="builtinassets",version="v1.4.2"} 1
# HELP windows_exporter_collector_duration_seconds windows_exporter: Duration of a collection.
# TYPE windows_exporter_collector_duration_seconds gauge
windows_exporter_collector_duration_seconds{collector="logical_disk"} 0
windows_exporter_collector_duration_seconds{collector="net"} 0
windows_exporter_collector_duration_seconds{collector="physical_disk"} 0
# HELP windows_exporter_collector_success windows_exporter: Whether the collector was successful.
# TYPE windows_exporter_collector_success gauge
windows_exporter_collector_success{collector="logical_disk"} 1
windows_exporter_collector_success{collector="net"} 1
windows_exporter_collector_success{collector="physical_disk"} 1
# HELP windows_exporter_collector_timeout windows_exporter: Whether the collector timed out.
# TYPE windows_exporter_collector_timeout gauge
windows_exporter_collector_timeout{collector="logical_disk"} 0
windows_exporter_collector_timeout{collector="net"} 0
windows_exporter_collector_timeout{collector="physical_disk"} 0
# HELP windows_exporter_perflib_snapshot_duration_seconds Duration of perflib snapshot capture
# TYPE windows_exporter_perflib_snapshot_duration_seconds gauge
windows_exporter_perflib_snapshot_duration_seconds 0.0014556
```
and that is all what is shown, there are no metrics at all of
```
windows_net_xxx
windows_logical_disk_xxx
windows_phisical_disk_xxx
```
while other windows metrics (like cpu, system, etc.) are actually exported normally

FYI: **Alloy v1.3.4** and **windows_exporter v0.29.1** are working correctly

### Steps to reproduce

On Windows Server 2022 Datacenter install Grafana Alloy 1.3.4, use attached config, open in browser [metrics path](http://localhost:12345/api/v0/component/prometheus.exporter.windows.testing/metrics) and see all of them are present:

```
# HELP windows_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, goversion from which windows_exporter was built, and the goos and goarch for the build.
# TYPE windows_exporter_build_info gauge
windows_exporter_build_info{branch="HEAD",goarch="amd64",goos="windows",goversion="go1.22.5",revision="88e779887",tags="builtinassets",version="v1.3.4"} 1
# HELP windows_exporter_collector_duration_seconds windows_exporter: Duration of a collection.
# TYPE windows_exporter_collector_duration_seconds gauge
windows_exporter_collector_duration_seconds{collector="logical_disk"} 0.0320621
windows_exporter_collector_duration_seconds{collector="net"} 4.16e-05
windows_exporter_collector_duration_seconds{collector="physical_disk"} 0.0003873
# HELP windows_exporter_collector_success windows_exporter: Whether the collector was successful.
# TYPE windows_exporter_collector_success gauge
windows_exporter_collector_success{collector="logical_disk"} 1
windows_exporter_collector_success{collector="net"} 1
windows_exporter_collector_success{collector="physical_disk"} 1
# HELP windows_exporter_collector_timeout windows_exporter: Whether the collector timed out.
# TYPE windows_exporter_collector_timeout gauge
windows_exporter_collector_timeout{collector="logical_disk"} 0
windows_exporter_collector_timeout{collector="net"} 0
windows_exporter_collector_timeout{collector="physical_disk"} 0
# HELP windows_exporter_perflib_snapshot_duration_seconds Duration of perflib snapshot capture
# TYPE windows_exporter_perflib_snapshot_duration_seconds gauge
windows_exporter_perflib_snapshot_duration_seconds 0.006464
# HELP windows_logical_disk_avg_read_requests_queued Average number of read requests that were queued for the selected disk during the sample interval (LogicalDisk.AvgDiskReadQueueLength)
# TYPE windows_logical_disk_avg_read_requests_queued gauge
windows_logical_disk_avg_read_requests_queued{volume="C:",volume_name="Local Disk"} 2585.9816283

and a whole list of related metrics below ...
```

Upgrade or do a clean install of Alloy 1.4.0 / 1.4.1 / 1.4.2 with the same config and see mentioned metrics are absent

### System information

Windows Server 2022 Datacenter, version 21H2, OS build 20348.887

### Software version

Grafana Alloy 1.4.0, Alloy 1.4.1, Alloy 1.4.2

### Configuration

config.alloy:
```
logging {
	level = "info"
}

prometheus.exporter.windows "node" {
  enabled_collectors = ["cpu", "cs", "os", "system", "mssql"]
}

prometheus.exporter.windows "testing" {
  enabled_collectors = ["net", "physical_disk", "logical_disk"]
}
```

========================================================================================

windows_exporter config.yaml for reference

```
log:
  level: warn
collectors:
  enabled: logical_disk,physical_disk,net
collector:
  service:
    include: windows_exporter
```

### Logs

From Windows EventLog

```
level=info msg="starting program" command="C:/Program Files/GrafanaLabs/Alloy/alloy-windows-amd64.exe run C:\\Program Files\\GrafanaLabs\\Alloy\\config.alloy --storage.path=C:\\ProgramData\\GrafanaLabs\\Alloy\\data --disable-reporting --server.http.enable-pprof=false --server.http.listen-addr=0.0.0.0:12345"

ts=2024-10-08T08:15:47.6325903Z level=info msg="no peer discovery configured: both join and discover peers are empty" service=cluster
ts=2024-10-08T08:15:47.6325903Z level=info msg="starting complete graph evaluation" controller_path=/ controller_id="" trace_id=d9e5080bcd73b22ef5342ccc0903856b
ts=2024-10-08T08:15:47.6325903Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=d9e5080bcd73b22ef5342ccc0903856b node_id=livedebugging duration=0s
ts=2024-10-08T08:15:47.6325903Z level=info msg="enabled windows_exporter collectors" component_path=/ component_id=prometheus.exporter.windows.testing collectors=logical_disk,net,physical_disk
ts=2024-10-08T08:15:47.6325903Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=d9e5080bcd73b22ef5342ccc0903856b node_id=prometheus.exporter.windows.testing duration=62.4166ms
ts=2024-10-08T08:15:47.6325903Z level=info msg="enabled windows_exporter collectors" component_path=/ component_id=prometheus.exporter.windows.node collectors=cpu,cs,mssql,os,system
ts=2024-10-08T08:15:47.6325903Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=d9e5080bcd73b22ef5342ccc0903856b node_id=prometheus.exporter.windows.node duration=0s
ts=2024-10-08T08:15:47.6325903Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=d9e5080bcd73b22ef5342ccc0903856b node_id=logging duration=0s
ts=2024-10-08T08:15:47.6346102Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=d9e5080bcd73b22ef5342ccc0903856b node_id=remotecfg duration=2.0199ms
ts=2024-10-08T08:15:47.6346102Z level=info msg="applying non-TLS config to HTTP server" service=http
ts=2024-10-08T08:15:47.6346102Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=d9e5080bcd73b22ef5342ccc0903856b node_id=http duration=0s
ts=2024-10-08T08:15:47.6346102Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=d9e5080bcd73b22ef5342ccc0903856b node_id=cluster duration=0s
ts=2024-10-08T08:15:47.6346102Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=d9e5080bcd73b22ef5342ccc0903856b node_id=ui duration=0s
ts=2024-10-08T08:15:47.6346102Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=d9e5080bcd73b22ef5342ccc0903856b node_id=otel duration=0s
ts=2024-10-08T08:15:47.6346102Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=d9e5080bcd73b22ef5342ccc0903856b node_id=labelstore duration=0s
ts=2024-10-08T08:15:47.6346102Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=d9e5080bcd73b22ef5342ccc0903856b node_id=tracing duration=0s

ts=2024-10-08T08:15:47.6325903Z level=info "boringcrypto enabled"=false

ts=2024-10-08T08:15:47.6346102Z level=info msg="finished complete graph evaluation" controller_path=/ controller_id="" trace_id=d9e5080bcd73b22ef5342ccc0903856b duration=64.4365ms
ts=2024-10-08T08:15:47.6346102Z level=info msg="scheduling loaded components and services"

ts=2024-10-08T08:15:47.6351612Z level=info msg="starting cluster node" service=cluster peers_count=0 peers="" advertise_addr=127.0.0.1:12345
ts=2024-10-08T08:15:47.6353867Z level=info msg="peers changed" service=cluster peers_count=1 peers=SQL1

ts=2024-10-08T08:15:47.636747Z level=info msg="now listening for http traffic" service=http addr=0.0.0.0:12345
```

### PR DESCRIPTION
**Pull request by ptodev**
#### PR Description

The default value of the `exclude` arguments at the moment is `""`. However, this is [causing](https://github.com/grafana/alloy/issues/1845#issuecomment-2402522821) the Windows Exporter to think that all collectors should be excluded, which leads to no metrics being gathered for that collector.

This issue is also present in the upstream exporter and was [fixed](https://github.com/prometheus-community/windows_exporter/pull/1679) recently.

This PR also fixes some inaccurate sections of the docs.

This PR should be merged after #1865, so that #1865 can be backported to older versions of Alloy.

cc @jkroepke 

#### Which issue(s) this PR fixes

Fixes #1845

#### PR Checklist

- [ ] CHANGELOG.md updated
- [x] Documentation added
- [x] Tests updated
- [ ] Config converters updated

### CODE REVIEW

File: internal/component/prometheus/exporter/windows/config.go [hunk 1]
```diff
@@ -135,6 +135,7 @@ func (t SMTPConfig) Convert() windows_integration.SMTPConfig {
 
 // ServiceConfig handles settings for the windows_exporter service collector
 type ServiceConfig struct {
+	//TODO: Should we make use_api and enable_v2_collector bool in Alloy v2?
```
Comment (jkroepke) [inline internal/component/prometheus/exporter/windows/config.go:138]: Both use_api and enable_v2_collector are removed in 0.29 anyways.

Comment (ptodev) [reply internal/component/prometheus/exporter/windows/config.go]: Thanks for letting me know, I removed this comment.

File: docs/sources/reference/components/prometheus/prometheus.exporter.windows.md [hunk 2]
```diff
@@ -83,51 +84,38 @@ text_file      | [text_file][]      | Configures the text_file collector.      |
...
-`exclude` | `string` | Regular expression of volumes to exclude. | `""`    | no
-`include` | `string` | Regular expression of volumes to include. | `".+"`  | no
+Name      | Type     | Description                               | Default   | Required
+----------|----------|-------------------------------------------|-----------|---------
+`exclude` | `string` | Regular expression of volumes to exclude. | `"^$"`    | no
+`include` | `string` | Regular expression of volumes to include. | `"^.+$"`  | no
 
 Volume names must match the regular expression specified by `include` and must _not_ match the regular expression specified by `exclude` to be included.
 
+User-supplied `exclude` and `include` strings will be [wrapped][wrap-regex] in a regex.
```
Comment (ptodev) [inline docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:118]: @mattdurham @clayton-cornell @jkroepke Are you happy with this explanation? And would you be ok with me raising a "v2 breaking change" issue for removing this regex wrapping?

File: docs/sources/reference/components/prometheus/prometheus.exporter.windows.md [hunk 3]
```diff
@@ -198,21 +192,21 @@ The v2 collector can query service states much more efficiently, but can't provi
 
 ### smb block
 
-Name           | Type     | Description                                                    | Default | Required
----------------|----------|----------------------------------------------------------------|---------|---------
-`enabled_list` | `string` | Deprecated (no-op), Comma-separated list of collectors to use. | `""`    | no
+Name           | Type           | Description                  | Default | Required
+---------------|----------------|------------------------------|---------|---------
+`enabled_list` | `list(string)` | A list of collectors to use. | `[]`    | no
```
[the remark this answers is not in the document]
Comment (jkroepke) [reply docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:205]: The collect is not deprecated. And there are no plan to deprecate it. Only the option `enabled_list` where removed, because there was only one sub-collector which make the whole flag pointless.

File: docs/sources/reference/components/prometheus/prometheus.exporter.windows.md [hunk 4]
```diff
@@ -45,24 +46,24 @@ Refer to the [Collectors list](#collectors-list) for the default set.
...
+msmq           | [msmq][]           | Configures the msmq collector.                    | no
+mssql          | [mssql][]          | Configures the mssql collector.                   | no
+network        | [network][]        | Configures the network collector.                 | no
+physical_disk  | [physical_disk][]  | Configures the physical_disk collector.           | no
+printer        | [printer][]        | Configures the printer collector.                 | no
+process        | [process][]        | Configures the process collector.                 | no
+scheduled_task | [scheduled_task][] | Configures the scheduled_task collector.          | no
+service        | [service][]        | Configures the service collector.                 | no
+smb            | [smb][]            | Configures the smb collector.                     | no
+smb_client     | [smb_client][]     | (Deprecated) Configures the smb_client collector. | no
```
Comment (jkroepke) [inline docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:64]:
```suggestion
smb_client     | [smb_client][]     | Configures the smb_client collector. | no
```

File: docs/sources/reference/components/prometheus/prometheus.exporter.windows.md [hunk 5]
```diff
@@ -268,6 +268,15 @@ debug information.
 `prometheus.exporter.windows` does not expose any component-specific
 debug metrics.
 
+[wrap-regex]: #wrapping-of-regex-strings
+## Wrapping of regex strings
```
Comment (jkroepke) [inline docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:272]: I recommend to add some notes and example and consequences here.

Regex as case sensitive. For case in sensitive match, use `(?i)` as prefix. 

Secondly, an example for the regex wrapping

Normally, a regex like `e.*` would match `email` and `design`. To avoid that, all regex are wrapped (as explained). If the original behavior is required, `.*` must be used as prefix, `.*e.*` would  `email` and `design` again.

File: docs/sources/reference/components/prometheus/prometheus.exporter.windows.md (hunk 2 above)
Comment (jkroepke) [reply docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:118]: If you ask me, I would link against every `Regular expression` on each Description to make it clearly visible.

Comment (ptodev) [reply docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:118]: That's a good idea, since we don't expect the wrapping to get in the way of users. It should be invisible, but we're documenting just as an FYI to users in case they experience something weird. @clayton-cornell, WDYT?

File: docs/sources/reference/components/prometheus/prometheus.exporter.windows.md (hunk 4 above)
Comment (ptodev) [reply docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:64]: I don't see an smb_client collector anymore:
https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.smb_client.md
Is it not deprecated?

File: docs/sources/reference/components/prometheus/prometheus.exporter.windows.md (hunk 3 above)
[the remark this answers is not in the document]
Comment (ptodev) [reply docs/sources/reference/components/prometheus/prometheus.exporter.windows.md]: Thank you, I brought back the "deprecated" note for `enabled_list` in the `smb` block.

File: docs/sources/reference/components/prometheus/prometheus.exporter.windows.md (hunk 4 above)
Comment (jkroepke) [reply docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:64]: The official name is [`smbclient`](https://github.com/prometheus-community/windows_exporter/blob/25d90212ce8a438e533b89ee98a7c6a3577ebb86/internal/collector/smbclient/smbclient.go#L18). 

https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.smbclient.md

File: docs/sources/reference/components/prometheus/prometheus.exporter.windows.md (hunk 5 above)
Comment (jkroepke) [reply docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:272]: > BTW according to [regex101.com](https://regex101.com/), e.* matches esign whereas ^(?:.*e.*)$ matches design - so they are not exactly equivalent?

But alloy wraps `e.*` into `^(?:e.*)$` which would not match design anymore. 

Ref: https://go.dev/play/p/yf5gxEZ3oeZ

Comment (ptodev) [reply docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:272]: I could add this note?
```
{{< admonition type="note" >}}
The wrapping may change the behaviour of your regex.
For example, the `e.*` regex would normally match both the "service" and "email" strings.
However, `^(?:e.*)$` would only match "email".
{{< /admonition >}}
```

File: internal/component/prometheus/exporter/windows/config.go [hunk 6]
```diff
@@ -1,11 +1,21 @@
...
 	windows_integration "github.com/grafana/alloy/internal/static/integrations/windows_exporter"
 )
 
+// Wrap some regex strings to prevent issues with user-supplied empty strings.
+// Prior to v0.27, the upstream exporter used to wrap regexes like this.
+// Alloy is now doing this instead, to maintain backwards compatibility.
+// See https://github.com/grafana/alloy/issues/1845
+// TODO: Remove this in Alloy v2.
+func wrapRegex(regex string) string {
+	return fmt.Sprintf("^(?:%s)$", regex)
```
Comment (mattdurham) [inline internal/component/prometheus/exporter/windows/config.go:16]: I am no regex master, would love a description of the behavior since the ticket takes a bit of reading to figure out whats going on.

**Review by mattdurham — APPROVED** [review]
One nit on some documentation but lgtm

File: docs/sources/reference/components/prometheus/prometheus.exporter.windows.md (hunk 4 above)
Comment (ptodev) [reply docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:64]: Ok thank you, I'll revert this change.

File: internal/component/prometheus/exporter/windows/config_default_windows_test.go [hunk 7]
```diff
@@ -44,3 +46,43 @@ func TestAlloyUnmarshalWithDefaultConfig(t *testing.T) {
...
+// This is a copy of the getDefaultPath() function in:
+// windows_exporter@v0.27.4-0.20241010144849-a0f6d3bcf9a4\pkg\collector\textfile\textfile.go
+func getDefaultTextFilePath() string {
+	execPath, _ := os.Executable()
+	return filepath.Join(filepath.Dir(execPath), "textfile_inputs")
+}
+
+func TestDefaultConfig(t *testing.T) {
+	// TODO: The BlackList and WhiteList attributes should be removed in Alloy v2.
+	// They are not even documented in Alloy v1.
```
[the remark this answers is not in the document]
Comment (ptodev) [reply internal/component/prometheus/exporter/windows/config_default_windows_test.go:59]: #1894

File: internal/component/prometheus/exporter/windows/config_default_windows_test.go
[the remark this answers is not in the document]
Comment (ptodev) [reply internal/component/prometheus/exporter/windows/config_default_windows_test.go:1]: `TestConvert` already does most of what I need, actually.

File: internal/component/prometheus/exporter/windows/config.go (hunk 6 above)
Comment (ptodev) [reply internal/component/prometheus/exporter/windows/config.go:21]: I updated the comment :) Is it ok?

File: docs/sources/reference/components/prometheus/prometheus.exporter.windows.md (hunk 2 above)
Comment (clayton-cornell) [inline docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:118]:
```suggestion
User-supplied `exclude` and `include` strings will be [wrapped][wrap-regex] in a regular expression.
```

Comment (clayton-cornell) [reply docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:118]: Linked the way it is now it's fairly clear to me on reading it all through and following the link to the regex explanation...

File: docs/sources/reference/components/prometheus/prometheus.exporter.windows.md [hunk 8]
```diff
@@ -268,6 +268,21 @@ debug information.
...
+
+Some collector blocks such as [scheduled_task][] accept a regular expression as a string argument.
+`prometheus.exporter.windows` will prefix some regex string arguments with `^(?:` and will suffix them with `)$`.
```
Comment (clayton-cornell) [inline docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:275]:
```suggestion
`prometheus.exporter.windows` will prefix some regular expression string arguments with `^(?:` and will suffix them with `)$`.
```

File: docs/sources/reference/components/prometheus/prometheus.exporter.windows.md [hunk 9]
```diff
@@ -268,6 +268,21 @@ debug information.
...
+For example, if a user sets an `exclude` argument to `".*"`, Alloy will set it to `"^(?:.*)$"`.
+
+To find out if a particular regex argument will be wrapped, refer to the collector block documentation.
```
Comment (clayton-cornell) [inline docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:278]:
```suggestion
To find out if a particular regular expression argument will be wrapped, refer to the collector block documentation.
```

Which block doc? Any based on whatever block they are using or a specific block?

File: docs/sources/reference/components/prometheus/prometheus.exporter.windows.md [hunk 10]
```diff
@@ -268,6 +268,21 @@ debug information.
...
+
+{{< admonition type="note" >}}
+The wrapping may change the behaviour of your regex.
+For example, the `e.*` regex would normally match both the "service" and "email" strings.
```
Comment (clayton-cornell) [inline docs/sources/reference/components/prometheus/prometheus.exporter.windows.md:282]:
```suggestion
The wrapping may change the behaviour of your regular expression.
For example, the `e.*` regular expression would normally match both the "service" and "email" strings.
```

File: docs/sources/reference/components/prometheus/prometheus.exporter.windows.md (hunk 2 above)
Comment (ptodev) [reply docs/sources/reference/components/prometheus/prometheus.exporter.windows.md]: I like how the current explanation clearly states "this is wrapped in this", and I wish I could say it clearly in the table itself in a concise way. I can't think of a concise way to do it though, so let's just merge it as it is since it's more clear.
