### PR TITLE
Fix internal namespace for certain components

### LINKED ISSUE #2802: Certain components cannot be run from modules
### What's wrong?

Certain components use the ID passed by their global options to construct a namespace they'll use for internal metrics. The component ID is sanitized, to avoid issues with dots in labels (before Prometheus got UTF-8 support).

https://github.com/grafana/alloy/blob/d0a7dd22c6120e778a1036a9a87db4c326b6b593/internal/component/loki/source/aws_firehose/component.go#L158

With the introduction of ways to run nested controllers (modules, remotecfg), this breaks as `/` is not a valid identifier for labels

### Steps to reproduce

Just run the provided configuration, either locally or served remotely.

### System information

macOS

### Software version

main (d0a7dd22c6120e778a1036a9a87db4c326b6b593)

### Configuration

```text
declare "foo" {
        loki.source.awsfirehose "loki_fh_receiver" {
            http {
                    listen_address = "0.0.0.0"
                    listen_port    = 9999
            }
            forward_to = [
                    loki.echo.default.receiver,
            ]
        }

        loki.echo "default" { }
}

foo "default" {}
```

### Logs

```text
./build/alloy run firehose.alloy
ts=2025-02-21T10:39:55.51181Z level=info "boringcrypto enabled"=false
ts=2025-02-21T10:39:55.511866Z level=info msg="no peer discovery configured: both join and discover peers are empty" service=cluster
ts=2025-02-21T10:39:55.511869Z level=info msg="running usage stats reporter"
ts=2025-02-21T10:39:55.511871Z level=info msg="starting complete graph evaluation" controller_path=/ controller_id="" trace_id=a321e666b101bd8c78f870912f5402cd
ts=2025-02-21T10:39:55.511887Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=a321e666b101bd8c78f870912f5402cd node_id=labelstore duration=24µs
ts=2025-02-21T10:39:55.511891Z level=info msg="starting complete graph evaluation" controller_path=/ controller_id=foo.default trace_id=7f752e20a94c8ae3b27bc9477b343986
ts=2025-02-21T10:39:55.511893Z level=info msg="finished node evaluation" controller_path=/ controller_id=foo.default trace_id=7f752e20a94c8ae3b27bc9477b343986 node_id=loki.echo.default duration=5.959µs
ts=2025-02-21T10:39:55.511896Z level=error msg="failed to evaluate config" controller_path=/ controller_id=foo.default trace_id=7f752e20a94c8ae3b27bc9477b343986 node=loki.source.awsfirehose.loki_fh_receiver err="building component: metrics namespace is not prometheus compatible: foo_default/loki_source_awsfirehose_loki_fh_receiver"
ts=2025-02-21T10:39:55.511901Z level=info msg="finished node evaluation" controller_path=/ controller_id=foo.default trace_id=7f752e20a94c8ae3b27bc9477b343986 node_id=loki.source.awsfirehose.loki_fh_receiver duration=2.161084ms
ts=2025-02-21T10:39:55.511904Z level=info msg="finished complete graph evaluation" controller_path=/ controller_id=foo.default trace_id=7f752e20a94c8ae3b27bc9477b343986 duration=2.186917ms
ts=2025-02-21T10:39:55.512879Z level=error msg="failed to evaluate config" controller_path=/ controller_id="" trace_id=a321e666b101bd8c78f870912f5402cd node=foo.default err="updating custom component: firehose.alloy:2:2: Failed to build component: building component: metrics namespace is not prometheus compatible: foo_default/loki_source_awsfirehose_loki_fh_receiver"
ts=2025-02-21T10:39:55.512886Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=a321e666b101bd8c78f870912f5402cd node_id=foo.default duration=2.213125ms
ts=2025-02-21T10:39:55.512889Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=a321e666b101bd8c78f870912f5402cd node_id=tracing duration=2.541µs
ts=2025-02-21T10:39:55.512892Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=a321e666b101bd8c78f870912f5402cd node_id=remotecfg duration=67.625µs
ts=2025-02-21T10:39:55.512895Z level=info msg="applying non-TLS config to HTTP server" service=http
ts=2025-02-21T10:39:55.512911Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=a321e666b101bd8c78f870912f5402cd node_id=http duration=5.875µs
ts=2025-02-21T10:39:55.512914Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=a321e666b101bd8c78f870912f5402cd node_id=cluster duration=542ns
ts=2025-02-21T10:39:55.512916Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=a321e666b101bd8c78f870912f5402cd node_id=otel duration=541ns
ts=2025-02-21T10:39:55.51292Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=a321e666b101bd8c78f870912f5402cd node_id=logging duration=1.127417ms
ts=2025-02-21T10:39:55.512926Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=a321e666b101bd8c78f870912f5402cd node_id=declare.foo duration=1.375µs
ts=2025-02-21T10:39:55.512932Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=a321e666b101bd8c78f870912f5402cd node_id=livedebugging duration=3.417µs
ts=2025-02-21T10:39:55.512937Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=a321e666b101bd8c78f870912f5402cd node_id=ui duration=583ns
ts=2025-02-21T10:39:55.512943Z level=info msg="finished complete graph evaluation" controller_path=/ controller_id="" trace_id=a321e666b101bd8c78f870912f5402cd duration=3.772875ms
Error: firehose.alloy:2:2: Failed to build component: building component: metrics namespace is not prometheus compatible: foo_default/loki_source_awsfirehose_loki_fh_receiver

 1 |   declare "foo" {
 2 |       loki.source.awsfirehose "loki_fh_receiver" {
   |  _____^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 3 | |         http {
 4 | |             listen_address = "0.0.0.0"
 5 | |             listen_port    = 9999
 6 | |         }
 7 | |         forward_to = [
 8 | |             loki.echo.default.receiver,
 9 | |         ]
10 | |     }
   | |_____^
11 |

Error: could not perform the initial load successfully
```

### PR DESCRIPTION
**Pull request by tpaschalis**
#### PR Description

This takes the easier route of sanitizing the component ID for nested controllers when it's used as a namespace for metrics.

#### Which issue(s) this PR fixes

Fixes #2802 

#### PR Checklist

- [X] CHANGELOG.md updated
- [ ] Documentation added (N/A)
- [ ] Tests updated (N/A) 
- [ ] Config converters updated (N/A)

### CODE REVIEW

File: internal/component/loki/source/gcplog/gcplog.go [hunk 1]
```diff
@@ -132,7 +132,7 @@ func (c *Component) Update(args component.Arguments) error {
 		}
 	}
 	entryHandler := loki.NewEntryHandler(c.handler.Chan(), func() {})
-	jobName := strings.Replace(c.opts.ID, ".", "_", -1)
+	jobName := strings.Replace(strings.Replace(c.opts.ID, ".", "_", -1), "/", "_", -1)
```
Comment (wildum) [inline internal/component/loki/source/gcplog/gcplog.go:135]: nit: instead of nesting the replace statements you could use a [string.Replacer](https://pkg.go.dev/strings#Replacer) (see the example for the usage) which is a bit more readable. This also scales better if one day we need to replace more characters

**Review by wildum — COMMENTED** [review]
Thanks for fixing this! Can you remove the .alloy and .log files please? If you could add a little unitest that would be nice

File: internal/component/loki/source/gcplog/gcplog.go (hunk 1 above)
Comment (tpaschalis) [reply internal/component/loki/source/gcplog/gcplog.go]: 🤦 sorry for the unintentionally comitted files. 

Here's the commit using strings.Replacer: 1acc64616e471e0dd5057a7d4a0a857cb643db8e

**Review by wildum — APPROVED** [review]

**Comment by tpaschalis** [comment]
cc @wildum added tests on https://github.com/grafana/alloy/pull/2803/commits/1959da62da0415589359cc0da1b2bfecb3b5f52f, verified they fail on main but pass here ^^

File: internal/component/loki/source/gcplog/gcplog_test.go [hunk 2]
```diff
@@ -26,6 +26,41 @@ import (
...
+		},
+	}
+	args.ForwardTo = []loki.LogsReceiver{ch1, ch2}
+	args.RelabelRules = exportedRules
+
+	// Create and run the component.
+	c, err := New(opts, args)
+	require.NoError(t, err)
+	require.NotNil(t, c)
+}
```
Comment (wildum) [inline internal/component/loki/source/gcplog/gcplog_test.go:62]: can you add a `defer goleak.VerifyNone` to both tests (you may need goleak.IgnoreTopFunction("go.opencensus.io/stats/view.(*worker).start")) please? I try to add this to any test that spawns go routines to catch mistakes and it can happen sometimes that leaked go routines from one test are making the goleak.VerifyNone of another test fail which makes it tricky to debug

Comment (tpaschalis) [reply internal/component/loki/source/gcplog/gcplog_test.go:65]: Yep, good catch, done! ^^

**Review by thampiotr — APPROVED** [review]
