### PR TITLE
ci: Allow release note enrichment when "closes" is present

### LINKED ISSUE #5297: foreach id doesn't work with discovery.file
### Component(s)

_No response_

### What's wrong?

The `foreach` component has an `id` parameter that's supposed to set the component name.  This works when the collection is passed inline, but it does not work when the collection comes from `discovery.file`. In this case, the `id` parameter seems to be ignored, and the component is named with a long random hash.

This example config includes 2 separate foreach blocks, one working and one not, as shown in these screenshots.

Image

Image

### Steps to reproduce

Using the attached config and run `alloy run xerus2.alloy --stability.level experimental`.

### System information

_No response_

### Software version

Grafana Alloy v1.12.2

### Configuration

```text
discovery.file "xerus_debug" {
  files = ["debug/alloy_targets/servertech_xerus.yml"]
}

foreach "xerus_debug_ok"  {
  collection = [
    {
      "__address__" = "10.59.31.124",
      "netbox_id" = "43356",
      "instance" = "10.59.31.124",
    },
  ]
  var = "each"
  id = "netbox_id"
  template {
    prometheus.scrape "xerus_debug" {
      forward_to = [prometheus.remote_write.debug.receiver]
      targets         = [each]
    }
  }
}

foreach "xerus_debug_nok"  {
  collection = discovery.file.xerus_debug.targets
  var = "each"
  id = "netbox_id"
  template {
    prometheus.scrape "xerus_debug" {
      forward_to = [prometheus.remote_write.debug.receiver]
      targets         = [each]
    }
  }
}

prometheus.remote_write "debug" {
  endpoint {
      url = "https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push"
      basic_auth {
        username = sys.env("PROMETHEUS_USER")
        password = sys.env("PROMETHEUS_TOKEN")
      }
  }
}
```

### Logs

```text

```

### Tip

<sub>React with 👍 if this issue is important to you.</sub>

### PR DESCRIPTION
**Pull request by jharvey10**
An interesting thing I discovered with release please is that if a commit has a reference to a closed issue, this will be called out in the changelog :tada:

For example:

```
* Invalid handling of id in foreach when using discovery components (#5322) (61fe184), closes #5297
```

The only problem is this breaks the way I wrote the regex for the release not enrichment script. This PR fixes that.

### CODE REVIEW

File: tools/release/enrich-release-notes/main.go [hunk 1]
```diff
@@ -13,6 +13,10 @@ import (
 	"github.com/grafana/alloy/tools/release/internal/version"
 )
 
+// commitPattern matches a commit SHA in markdown link format: "([abc1234](https://github.com/.../commit/...))"
+// It captures the short SHA from the link text, regardless of surrounding context.
+var commitPattern = regexp.MustCompile(`\(\[([a-f0-9]{7,40})\]\(https://github\.com/[^)]+\)\)`)
```
Comment (jharvey10) [inline tools/release/enrich-release-notes/main.go:18]: the main difference is the absence of `\s*$`
