### PR TITLE
fix(import/git): fix panic when use non-existent revision on remote

### LINKED ISSUE #968: Alloy panic when using import.git if revision doesn't exist on remote repo
### What's wrong?

Alloy's `import.git` component causes Alloy to panic  if you set `revision` to one that does not exist in the repo. (The example in our component reference docs says `revision="master"`, so before I changed that from the default, I caught this right away.) 

### Steps to reproduce

See the comments in the configuration section below. (alloy.config and .env examples provided.)

### System information

Docker, Docker compose

### Software version

latest public docker image as of 5/30/24 at 11AM

### Configuration

```text
// At the moment, this can be reproduced if you include this in alloy.config,
import.git "logs_module" {
  repository 		= env("LOGS_MODULE_REPOSITORY")
  revision   		= env("LOGS_MODULE_REVISION")
  path       		= env("LOGS_MODULE_PATH")
  pull_frequency	= env("LOGS_MODULE_PULL_FREQUENCY")
}


# and here are some non-sensitive values you can use on that if it's helpful:
LOGS_MODULE_REPOSITORY="https://github.com/danstadler-pdx/grafana-alloy-pii-demo.git"
LOGS_MODULE_REVISION="master"
LOGS_MODULE_PATH="demo02-docker/modules/my-log-processor.alloy"
LOGS_MODULE_PULL_FREQUENCY="60m"
```

### Logs

```text
danstadler@dans-mbp demo02-docker % docker-compose up
[+] Running 4/4
 ✔ Network demo02-docker_default          Created                                                                                              0.1s
 ✔ Volume "demo02-docker_loggerapp_logs"  Created                                                                                              0.0s
 ✔ Container loggerapp                    Created                                                                                              0.2s
 ✔ Container alloy                        Created                                                                                              0.2s
Attaching to alloy, loggerapp
alloy      | interrupt received
alloy      | panic: runtime error: invalid memory address or nil pointer dereference
alloy      | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x166fb1c]
alloy      |
alloy      | goroutine 1 [running]:
alloy      |
alloy      | github.com/grafana/alloy/internal/vcs.(*GitRepo).Update(0x0, {0x8717a68, 0xd5c7240})
alloy      | 	/src/alloy/internal/vcs/git.go:115 +0x2c
alloy      | github.com/grafana/alloy/internal/alloy/internal/importsource.(*ImportGit).pollFile(0x40031c4900, {0x8717a68?, 0xd5c7240?}, {{0x400007c017, 0x3c}, {0x400007a035, 0x6}, {0x4000078051, 0x2c}, 0x34630b8a000, ...})
alloy      | 	/src/alloy/internal/alloy/internal/importsource/import_git.go:233 +0x54
alloy      | github.com/grafana/alloy/internal/alloy/internal/importsource.(*ImportGit).Update(0x40031c4900, {0x6dc0760, 0x40036e85b8})
alloy      | 	/src/alloy/internal/alloy/internal/importsource/import_git.go:208 +0x410
alloy      | github.com/grafana/alloy/internal/alloy/internal/importsource.(*ImportGit).Evaluate(0x40031c4900, 0x400247df60)
alloy      | 	/src/alloy/internal/alloy/internal/importsource/import_git.go:83 +0x118
alloy      | github.com/grafana/alloy/internal/alloy/internal/controller.(*ImportConfigNode).Evaluate(0x40020952c0, 0x175fad4?)
alloy      | 	/src/alloy/internal/alloy/internal/controller/node_config_import.go:179 +0x30
alloy      | github.com/grafana/alloy/internal/alloy/internal/controller.(*Loader).evaluate(0x40031d81a0, {0x869de20, 0x40031b7ea0}, {0x8718d80, 0x40020952c0})
alloy      | 	/src/alloy/internal/alloy/internal/controller/loader.go:831 +0x50
alloy      | github.com/grafana/alloy/internal/alloy/internal/controller.(*Loader).Apply.func2({0x86a0700, 0x40020952c0})
alloy      | 	/src/alloy/internal/alloy/internal/controller/loader.go:233 +0x8a4
alloy      | github.com/grafana/alloy/internal/alloy/internal/dag.WalkTopological(0x40031f0800, {0x4002f7db00, 0x9, 0xcad7470?}, 0x40036e9280)
alloy      | 	/src/alloy/internal/alloy/internal/dag/walk.go:83 +0x194
alloy      | github.com/grafana/alloy/internal/alloy/internal/controller.(*Loader).Apply(0x40031d81a0, {0x0, {0x40031b5c00, 0x8, 0x8}, {0x40031f07c0, 0x3, 0x4}, {0x0, 0x0, ...}, ...})
alloy      | 	/src/alloy/internal/alloy/internal/controller/loader.go:184 +0x868
alloy      | github.com/grafana/alloy/internal/alloy.(*Alloy).loadSource(0x40003990e0, 0x40031da230, 0x0, 0x0)
alloy      | 	/src/alloy/internal/alloy/alloy.go:310 +0x134
alloy      | github.com/grafana/alloy/internal/alloy.(*Alloy).LoadSource(...)
alloy      | 	/src/alloy/internal/alloy/alloy.go:294
alloy      | github.com/grafana/alloy/internal/alloycli.(*alloyRun).Run.func4()
alloy      | 	/src/alloy/internal/alloycli/cmd_run.go:312 +0x1f4
alloy      | github.com/grafana/alloy/internal/alloycli.(*alloyRun).Run(0x4000398f00, {0xffffc500ed3b, 0x17})
alloy      | 	/src/alloy/internal/alloycli/cmd_run.go:345 +0xce8
alloy      | github.com/grafana/alloy/internal/alloycli.runCommand.func1(0x4002f7c900?, {0x40031ba7e0?, 0x4?, 0x73f3237?})
alloy      | 	/src/alloy/internal/alloycli/cmd_run.go:101 +0x38
alloy      | github.com/spf13/cobra.(*Command).execute(0x40020f3508, {0x40031ba750, 0x3, 0x3})
alloy      | 	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
alloy      | github.com/spf13/cobra.(*Command).ExecuteC(0x40020f2c08)
alloy      | 	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
alloy      | github.com/spf13/cobra.(*Command).Execute(...)
alloy      | 	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
alloy      | github.com/grafana/alloy/internal/alloycli.Run()
alloy      | 	/src/alloy/internal/alloycli/alloycli.go:33 +0x2e8
alloy      | main.main()
alloy      | 	/src/alloy/main.go:34 +0x1c
alloy exited with code 2
```

### PR DESCRIPTION
**Pull request by hainenber**
#### Which issue(s) this PR fixes

Fixes #968 

#### PR Checklist

- [x] CHANGELOG.md updated
- [x] Tests updated

### CODE REVIEW

**Review by wildum — COMMENTED** [review]
Thanks for taking care of this! I believe that the fix works but I wonder if it would not be better to return a different error than UpdateFailedError in the vcs package for the initial checkout: https://github.com/grafana/alloy/blob/main/internal/vcs/git.go#L99
@mattdurham wdyt?

**Comment by mattdurham** [comment]
Pretty reasonable, what I think would add even more context is if we added additional information with including the reference id after we check the error type. Current it returns something like  `reference not found` it would be awesome if it returned something like `"nonexistent" reference not found`

Something like this

```
if errors.Is(err, plumbing.ErrReferenceNotFound) || !isUpdateFailedError {
				return fmt.Errorf("could not find reference \"%s\" %w", newArgs.Revision, err)
			}
```

Its a little repetitive so can def change the wording or just do `%w %s`?

File: internal/runtime/internal/importsource/import_git.go [hunk 1]
```diff
@@ -194,11 +195,13 @@ func (im *ImportGit) Update(args component.Arguments) (err error) {
 	if im.repo == nil || !reflect.DeepEqual(repoOpts, im.repoOpts) {
 		r, err := vcs.NewGitRepo(context.Background(), repoPath, repoOpts)
 		if err != nil {
-			if errors.As(err, &vcs.UpdateFailedError{}) {
+			isUpdateFailedError := errors.As(err, &vcs.UpdateFailedError{})
+			if errors.Is(err, plumbing.ErrReferenceNotFound) || !isUpdateFailedError {
+				return err
+			}
+			if isUpdateFailedError {
```
[the remark this answers is not in the document]
Comment (hainenber) [reply internal/runtime/internal/importsource/import_git.go:198]: Oh, this "if" condition is to catch when `isUpdateFailedError` is true though :D

**Comment by hainenber** [comment]
Fellas, I've changed the error type to something already in place, `InvalidRevisionError`, to contain more metadata. PTAL :D

File: internal/vcs/git.go [hunk 2]
```diff
@@ -96,6 +96,9 @@ func NewGitRepo(ctx context.Context, storagePath string, opts GitRepoOptions) (*
 
 	checkoutErr := checkout(opts.Revision, repo)
 	if checkoutErr != nil {
+		if errors.Is(checkoutErr, plumbing.ErrReferenceNotFound) {
+			return nil, InvalidRevisionError{opts.Revision}
+		}
 		return nil, UpdateFailedError{
```
Comment (wildum) [inline internal/vcs/git.go:102]: just for consistency, could we return checkoutErr instead of UpdateFailedError?
If this code returns nil, UpdateFailedError at this stage, it would panic like it did in the ticket. I don't think that it's possible right now that it happens but it makes the code more robust

File: internal/runtime/internal/importsource/import_git.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (wildum) [reply internal/runtime/internal/importsource/import_git.go:198]: When I commented the order was different but the idea was that if you check that isUpdateFailedError is false above and that you return, then in the code that follows isUpdateFailedError will be true

if A || !B {
 return
}
if B { <----- the condition is not needed because B will always be true since we return when B is false above
  foo()
}

This is not relevant anymore though

File: internal/runtime/internal/importsource/import_git.go [hunk 3]
```diff
@@ -194,10 +194,12 @@ func (im *ImportGit) Update(args component.Arguments) (err error) {
...
 		r, err := vcs.NewGitRepo(context.Background(), repoPath, repoOpts)
 		if err != nil {
-			if errors.As(err, &vcs.UpdateFailedError{}) {
+			isUpdateFailedError := errors.As(err, &vcs.UpdateFailedError{})
+			if isUpdateFailedError {
 				level.Error(im.log).Log("msg", "failed to update repository", "err", err)
 				im.updateHealth(err)
-			} else {
+			}
+			if errors.As(err, &vcs.InvalidRevisionError{}) || !isUpdateFailedError {
```
Comment (wildum) [inline internal/runtime/internal/importsource/import_git.go:202]: I think that with the change that was made in git.go, we can keep the original version of the code for this file because InvalidRevisionError is not an isUpdateFailedError error.

Comment (hainenber) [reply internal/runtime/internal/importsource/import_git.go]: Makes sense to me. Updated in HEAD :D

**Review by wildum — APPROVED** [review]
Thank you! As always, your contributions are very much appreciated :)
