### PR TITLE
fix: Skip explain plans which lookup individual records and return no rows 

### LINKED ISSUE #4987: gracefully handle queries which do not return any rows when running explain plan
### Component(s)

database_observability.mysql

### Add a description

When a query is executed with a `WHERE` clause which does not return a row, the resulting explain plan is empty.

For example `select last_name from employees where emp_no = 1;` will not return any rows and the resulting in a native explain plan that looks like this.

```
{
  "query_block": {
    "select_id": 1,
    "message": "no matching row in const table"
  }
}
```

The same query with an employee number that exists, I.E. `select last_name from employees where emp_no = 10001;` will produce a useful explain plan.

The `QUERY_SAMPLE_TEXT` in `performance_schema.events_statements_summary_by_digest` will contain the most recent concrete query that was executed for a given digest, possibly resulting in inconsistent explain plans, sometimes containing explain details or being empty as shown above.

We need to detect if the query sample will result in any returned rows, and not send an empty explain plan in that case.

### Tip

<sub>React with 👍 if this issue is important to you.</sub>

### PR DESCRIPTION
**Pull request by rgeyer**
### Brief description of Pull Request
In MySQL, the query we're executing for explain plans gets an updated concrete query in `performance_schema` periodically.

For queries which look up a single row, by a primary key id, for a record which does not exist, no explain plan is created.

This created situations where a customer would sometimes see an explain plan, and sometimes not for a given query.

This PR simply refrains from logging the empty explain plan, such that the dbo11y UI should only find explain plan records with content for a given query.

### Issue(s) fixed by this Pull Request
Fixes #4987

### Notes to the Reviewer
This just debug logs the fact that we're skipping, and does not communicate with the user or the dbo11y UI in any way.

In the future, I'd like to add some additional telemetry which a user can opt-in to with their alloy config to have more visibility to the frequency with which individual queries are dropped for the various reasons.

### PR Checklist
- [x] Tests updated

BEGIN_COMMIT_OVERRIDE
fix(database_observability): Skip explain plans which lookup individual records and return no rows (#5203)
END_COMMIT_OVERRIDE

### CODE REVIEW

File: internal/component/database_observability/mysql/collector/explain_plans.go [hunk 1]
```diff
@@ -692,6 +692,14 @@ func (c *ExplainPlans) fetchExplainPlans(ctx context.Context) error {
 			continue
 		}
 
+		msgBlock, _, _, err := jsonparser.Get(redactedByteExplainPlanJSON, "query_block", "message")
+		if err == nil {
```
Comment (cristiangreco) [inline internal/component/database_observability/mysql/collector/explain_plans.go]: Just checking: if `err != nil` are we happy not doing anything and moving on?

**Review by cristiangreco — APPROVED** [review]

File: internal/component/database_observability/mysql/collector/explain_plans.go (hunk 1 above)
Comment (rgeyer) [reply internal/component/database_observability/mysql/collector/explain_plans.go]: I think yes. The most likely scenario is that it did not find the requested json node.

That said, this is probably not the most deterministic way to handle it. I should check for error, and empty string separately.
