### PR TITLE
http: fix pathPrefix used to look up remotecfg's components

### LINKED ISSUE #1486: remotecfg not registering components
### What's wrong?

I am using the public-preview feature `remotecfg` with a custom implementation of the RPC protocol.
I have confirmed that the service implementation works, I properly get configs in /var/lib/alloy/data/remotecfg/<hash> and 
/var/lib/alloy/data/remotecfg/<components with state> (such as prometheus.remote_write.mimir)

Even though the config gets loaded, the components don't get registered to the api, so when the scrape component runs the API endpoint gives a 400.
```
Aug 16 15:29:45 localhost alloy[353876]: ts=2024-08-16T19:29:45.498238958Z level=debug msg="Scrape failed" component_path=/remotecfg component_id=prometheus.scrape.unix_exporter scrape_pool=remotecfg/prometheus.scrape.unix_exporter target=http://alloy.internal:12345/api/v0/component/remotecfg/prometheus.exporter.unix.default/metrics err="server returned HTTP status 400 Bad Request"
```

When going to localhost:12345/api/v0/web/components, the list of defined components is entirely empty.
When putting the same config into /etc/alloy/config.alloy instead, the list of components is fully populated.

### Steps to reproduce

1. have working remotecfg service implementation,
2. run alloy with /etc/alloy/config.alloy, with id=constants.hostname served by remotecfg service
3. Check http://localhost:12345/api/v0/web/components

### System information

Linux 6.6.9-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jan  1 20:05:54 UTC 2024 x86_64 GNU/Linux

### Software version

alloy, version v1.3.0 (branch: HEAD, revision: 281586f58)   build user:       root@87245c8d1fdf   build date:       2024-08-05T12:57:18Z   go version:       go1.22.5   platform:         linux/amd64   tags:             netgo,builtinassets,promtail_journal_enabled

### Configuration

```text
/etc/alloy/config.alloy

logging {
  level = "debug"
}

remotecfg {
  url = "<URL>"
  id             = constants.hostname
  poll_frequency = "5m"
}
```

config returned by the remotecfg implementation:
```
prometheus.exporter.unix "default" {}

prometheus.scrape "unix_exporter" {
  targets    = prometheus.exporter.unix.default.targets
  forward_to = [prometheus.remote_write.mimir.receiver]
}

prometheus.remote_write "mimir" {
  endpoint {
      url = "https://<MIMIR_ID>/api/v1/push"
      headers = {
        "X-Scope-OrgID" = "<TENANTID>",
      }
  }
}
```
```


### Logs

```text
Aug 16 15:46:05 hostname dbus-daemon[357821]: [session uid=969 pid=357819] SELinux support is enabled
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.2178641Z level=info "boringcrypto enabled"=false
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.217436403Z level=info source=/go/pkg/mod/github.com/!kim!machine!gun/automemlimit@v0.6.0/memlimit/memlimit.go:170 msg="memory is not limited, skipping: %v" package=github.com/KimMachineGun/automemlimit/memlimit !BADKEY="memory is not limited"
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.217898068Z level=info msg="running usage stats reporter"
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.217900674Z level=info msg="starting complete graph evaluation" controller_path=/ controller_id="" trace_id=ee9cfc7917b54aa4a5acca57a5e1b4bd
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.217906283Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=ee9cfc7917b54aa4a5acca57a5e1b4bd node_id=tracing duration=2.795µs
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.217911359Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=ee9cfc7917b54aa4a5acca57a5e1b4bd node_id=logging duration=64.024µs
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.378738905Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=ee9cfc7917b54aa4a5acca57a5e1b4bd node_id=remotecfg duration=160.819799ms
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.378769472Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=ee9cfc7917b54aa4a5acca57a5e1b4bd node_id=otel duration=1.47µs
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.378789871Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=ee9cfc7917b54aa4a5acca57a5e1b4bd node_id=livedebugging duration=10.796µs
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.378799362Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=ee9cfc7917b54aa4a5acca57a5e1b4bd node_id=labelstore duration=2.13µs
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.378807925Z level=info msg="applying non-TLS config to HTTP server" service=http
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.378812508Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=ee9cfc7917b54aa4a5acca57a5e1b4bd node_id=http duration=7.662µs
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.378818222Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=ee9cfc7917b54aa4a5acca57a5e1b4bd node_id=cluster duration=346ns
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.378823799Z level=info msg="finished node evaluation" controller_path=/ controller_id="" trace_id=ee9cfc7917b54aa4a5acca57a5e1b4bd node_id=ui duration=301ns
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.378828304Z level=info msg="finished complete graph evaluation" controller_path=/ controller_id="" trace_id=ee9cfc7917b54aa4a5acca57a5e1b4bd duration=161.039125ms
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.378842472Z level=debug msg="changing node state" service=cluster from=viewer to=participant
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.378851078Z level=debug msg="hostname @1: participant" service=cluster
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.378940116Z level=info msg="scheduling loaded components and services"
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.379002091Z level=info msg="starting cluster node" service=cluster peers_count=0 peers="" advertise_addr=127.0.0.1:12345
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.379030844Z level=debug msg="hostname @3: participant" service=cluster
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.379136869Z level=info msg="peers changed" service=cluster peers_count=1 peers=hostname
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.379280724Z level=info msg="now listening for http traffic" service=http addr=127.0.0.1:12345
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609033887Z level=info msg="starting complete graph evaluation" controller_path=/ controller_id=remotecfg trace_id=89b2cc3c2dd6f51535dd564b5022b0cb
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609523837Z level=info msg="Parsed flag --collector.diskstats.device-exclude" component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=diskstats flag=^(ram|loop|fd|(h|s|v|xv)d[a-z]|nvme\d+n\d+p)\d+$
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609819208Z level=info msg="Parsed flag --collector.filesystem.mount-points-exclude" component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=filesystem flag=^/(dev|proc|run/credentials/.+|sys|var/lib/docker/.+)($|/)
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609827593Z level=info msg="Parsed flag --collector.filesystem.fs-types-exclude" component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=filesystem flag=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609913756Z level=info msg="Enabled node_exporter collectors" component_path=/remotecfg component_id=prometheus.exporter.unix.default
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609923784Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=arp
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609927152Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=bcache
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609929779Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=bonding
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609932222Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=btrfs
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.60993781Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=conntrack
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609940514Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=cpu
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609943011Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=cpufreq
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609945479Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=diskstats
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609948196Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=dmi
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.60995071Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=edac
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609953189Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=entropy
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609955544Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=fibrechannel
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609957889Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=filefd
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609962574Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=filesystem
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609965349Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=hwmon
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609969853Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=infiniband
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609972555Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=ipvs
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609974929Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=loadavg
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.60997742Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=mdadm
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609979919Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=meminfo
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609982858Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=netclass
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609985392Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=netdev
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609987744Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=netstat
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609990518Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=nfs
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609992901Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=nfsd
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609995387Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=nvme
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.609997914Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=os
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610000466Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=powersupplyclass
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610003141Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=pressure
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610005587Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=processes
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610008058Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=rapl
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.61001377Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=schedstat
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610016462Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=selinux
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610018976Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=sockstat
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610021549Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=softnet
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610024014Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=stat
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610026366Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=tapestats
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610029821Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=textfile
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610034474Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=thermal_zone
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610037293Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=time
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610040562Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=timex
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610043127Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=udp_queues
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610045694Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=uname
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610048045Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=vmstat
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610050515Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=xfs
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610053156Z level=info component_path=/remotecfg component_id=prometheus.exporter.unix.default collector=zfs
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.610062588Z level=info msg="finished node evaluation" controller_path=/ controller_id=remotecfg trace_id=89b2cc3c2dd6f51535dd564b5022b0cb node_id=prometheus.exporter.unix.default duration=968.6µs
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.613847998Z level=info msg="replaying WAL, this may take a while" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=wal dir=/var/lib/alloy/data/remotecfg/prometheus.remote_write.mimir/wal
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.61396509Z level=info msg="WAL segment loaded" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=wal segment=0 maxSegment=0
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.614473928Z level=info msg="Starting WAL watcher" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push queue=eff791
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.614485986Z level=info msg="Starting scraped metadata watcher" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.614498326Z level=info msg="finished node evaluation" controller_path=/ controller_id=remotecfg trace_id=89b2cc3c2dd6f51535dd564b5022b0cb node_id=prometheus.remote_write.mimir duration=4.42446ms
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.614518005Z level=info msg="Replaying WAL" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push queue=eff791
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.614584733Z level=debug msg="Tailing WAL" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lastCheckpoint="" checkpointIndex=0 currentSegment=0
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.61460657Z level=debug msg="Processing segment" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push currentSegment=0 lastSegment=0
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.647980046Z level=debug msg="scrape config was updated" component_path=/remotecfg component_id=prometheus.scrape.unix_exporter
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.648005007Z level=info msg="finished node evaluation" controller_path=/ controller_id=remotecfg trace_id=89b2cc3c2dd6f51535dd564b5022b0cb node_id=prometheus.scrape.unix_exporter duration=33.494866ms
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.648017443Z level=info msg="finished complete graph evaluation" controller_path=/ controller_id=remotecfg trace_id=89b2cc3c2dd6f51535dd564b5022b0cb duration=39.036117ms
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.67537065Z level=info msg="scheduling loaded components and services"
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.675429085Z level=debug msg="passed new targets to scrape manager" component_path=/remotecfg component_id=prometheus.scrape.unix_exporter
Aug 16 15:46:05 hostname alloy[357803]: ts=2024-08-16T19:46:05.675519098Z level=debug msg="finished node evaluation" controller_path=/ controller_id=remotecfg node_id=prometheus.scrape.unix_exporter duration=67.749µs
Aug 16 15:46:20 hostname alloy[357803]: ts=2024-08-16T19:46:20.615249779Z level=debug msg="Watcher is reading the WAL due to timeout, haven't received any write notifications recently" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push timeout=15s
Aug 16 15:46:45 hostname alloy[357803]: ts=2024-08-16T19:46:45.498140649Z level=debug msg="dialed to in-memory listener" service=http
Aug 16 15:46:45 hostname alloy[357803]: ts=2024-08-16T19:46:45.498199847Z level=debug msg="accepted new in-memory connection" service=http
Aug 16 15:46:45 hostname alloy[357803]: 2024/08/16 15:46:45 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.getRRW.func2.1 (mux.go:114)
Aug 16 15:46:45 hostname alloy[357803]: ts=2024-08-16T19:46:45.498492004Z level=debug msg="Scrape failed" component_path=/remotecfg component_id=prometheus.scrape.unix_exporter scrape_pool=remotecfg/prometheus.scrape.unix_exporter target=http://alloy.internal:12345/api/v0/component/remotecfg/prometheus.exporter.unix.default/metrics err="server returned HTTP status 400 Bad Request"
Aug 16 15:46:45 hostname alloy[357803]: ts=2024-08-16T19:46:45.498641447Z level=info msg="Done replaying WAL" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push duration=39.884133462s
Aug 16 15:46:45 hostname alloy[357803]: ts=2024-08-16T19:46:45.617765702Z level=debug msg="runShard timer ticked, sending buffered data" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push samples=5 exemplars=0 shard=0 histograms=0
Aug 16 15:46:55 hostname alloy[357803]: ts=2024-08-16T19:46:55.614936705Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.5 dataOutRate=0.5 dataKeptRatio=1 dataPendingRate=0 dataPending=0 dataOutDuration=0.017743106 timePerSample=0.035486212 desiredShards=0.017743106 highestSent=1.723837605e+09 highestRecv=1.723837605e+09
Aug 16 15:46:55 hostname alloy[357803]: ts=2024-08-16T19:46:55.615070203Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.017743106 upperBound=1.3
Aug 16 15:47:05 hostname alloy[357803]: ts=2024-08-16T19:47:05.615502764Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.32 dataOutRate=0.4 dataKeptRatio=1 dataPendingRate=-0.08000000000000002 dataPending=0 dataOutDuration=0.0141944848 timePerSample=0.035486211999999996 desiredShards=0.011355587839999999 highestSent=1.723837605e+09 highestRecv=1.723837605e+09
Aug 16 15:47:05 hostname alloy[357803]: ts=2024-08-16T19:47:05.615530702Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.011355587839999999 upperBound=1.3
Aug 16 15:47:15 hostname alloy[357803]: ts=2024-08-16T19:47:15.614789553Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.32 dataOutRate=0.32 dataKeptRatio=1 dataPendingRate=0 dataPending=0 dataOutDuration=0.01135558784 timePerSample=0.035486212 desiredShards=0.01135558784 highestSent=1.723837605e+09 highestRecv=1.723837605e+09
Aug 16 15:47:15 hostname alloy[357803]: ts=2024-08-16T19:47:15.614815995Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.01135558784 upperBound=1.3
Aug 16 15:47:25 hostname alloy[357803]: ts=2024-08-16T19:47:25.61527981Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.2048 dataOutRate=0.256 dataKeptRatio=1 dataPendingRate=-0.051199999999999996 dataPending=0 dataOutDuration=0.009084470272 timePerSample=0.035486211999999996 desiredShards=0.007267576217599999 highestSent=1.723837605e+09 highestRecv=1.723837605e+09
Aug 16 15:47:25 hostname alloy[357803]: ts=2024-08-16T19:47:25.615306107Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.007267576217599999 upperBound=1.3
Aug 16 15:47:30 hostname alloy[357803]: ts=2024-08-16T19:47:30.501015615Z level=debug msg="Watcher is reading the WAL due to timeout, haven't received any write notifications recently" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push timeout=15s
Aug 16 15:47:35 hostname alloy[357803]: ts=2024-08-16T19:47:35.614674249Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.16384 dataOutRate=0.2048 dataKeptRatio=1 dataPendingRate=-0.040959999999999996 dataPending=0 dataOutDuration=0.0072675762176 timePerSample=0.035486211999999996 desiredShards=0.00581406097408 highestSent=1.723837605e+09 highestRecv=1.723837605e+09
Aug 16 15:47:35 hostname alloy[357803]: ts=2024-08-16T19:47:35.614702335Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.00581406097408 upperBound=1.3
Aug 16 15:47:45 hostname alloy[357803]: 2024/08/16 15:47:45 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.getRRW.func2.1 (mux.go:114)
Aug 16 15:47:45 hostname alloy[357803]: ts=2024-08-16T19:47:45.498597713Z level=debug msg="Scrape failed" component_path=/remotecfg component_id=prometheus.scrape.unix_exporter scrape_pool=remotecfg/prometheus.scrape.unix_exporter target=http://alloy.internal:12345/api/v0/component/remotecfg/prometheus.exporter.unix.default/metrics err="server returned HTTP status 400 Bad Request"
Aug 16 15:47:45 hostname alloy[357803]: ts=2024-08-16T19:47:45.614669257Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.16384 dataOutRate=0.16384 dataKeptRatio=1 dataPendingRate=0 dataPending=9.830400000000001 dataOutDuration=0.00581406097408 timePerSample=0.035486211999999996 desiredShards=0.02325624389632 highestSent=1.723837605e+09 highestRecv=1.723837665e+09
Aug 16 15:47:45 hostname alloy[357803]: ts=2024-08-16T19:47:45.614705217Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.02325624389632 upperBound=1.3
Aug 16 15:47:45 hostname alloy[357803]: ts=2024-08-16T19:47:45.801685131Z level=debug msg="runShard timer ticked, sending buffered data" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push samples=5 exemplars=0 shard=0 histograms=0
Aug 16 15:47:55 hostname alloy[357803]: ts=2024-08-16T19:47:55.614558407Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.1848576 dataOutRate=0.231072 dataKeptRatio=1 dataPendingRate=-0.04621439999999999 dataPending=0 dataOutDuration=0.007720339199264 timePerSample=0.033410968006785766 desiredShards=0.006176271359411201 highestSent=1.723837665e+09 highestRecv=1.723837665e+09
Aug 16 15:47:55 hostname alloy[357803]: ts=2024-08-16T19:47:55.614586257Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.006176271359411201 upperBound=1.3
Aug 16 15:48:05 hostname alloy[357803]: ts=2024-08-16T19:48:05.614904095Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.14788608 dataOutRate=0.1848576 dataKeptRatio=1 dataPendingRate=-0.03697152000000001 dataPending=0 dataOutDuration=0.0061762713594112 timePerSample=0.033410968006785766 desiredShards=0.0049410170875289604 highestSent=1.723837665e+09 highestRecv=1.723837665e+09
Aug 16 15:48:05 hostname alloy[357803]: ts=2024-08-16T19:48:05.614967458Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.0049410170875289604 upperBound=1.3
Aug 16 15:48:15 hostname alloy[357803]: ts=2024-08-16T19:48:15.615337726Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.118308864 dataOutRate=0.14788608 dataKeptRatio=1 dataPendingRate=-0.029577216000000003 dataPending=0 dataOutDuration=0.0049410170875289604 timePerSample=0.033410968006785766 desiredShards=0.003952813670023168 highestSent=1.723837665e+09 highestRecv=1.723837665e+09
Aug 16 15:48:15 hostname alloy[357803]: ts=2024-08-16T19:48:15.615371833Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.003952813670023168 upperBound=1.3
Aug 16 15:48:25 hostname alloy[357803]: ts=2024-08-16T19:48:25.614721214Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.118308864 dataOutRate=0.118308864 dataKeptRatio=1 dataPendingRate=0 dataPending=0 dataOutDuration=0.003952813670023168 timePerSample=0.033410968006785766 desiredShards=0.003952813670023168 highestSent=1.723837665e+09 highestRecv=1.723837665e+09
Aug 16 15:48:35 hostname alloy[357803]: ts=2024-08-16T19:48:35.615529209Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.07571767296000001 dataOutRate=0.0946470912 dataKeptRatio=1 dataPendingRate=-0.018929418239999996 dataPending=0 dataOutDuration=0.003162250936018535 timePerSample=0.033410968006785766 desiredShards=0.002529800748814828 highestSent=1.723837665e+09 highestRecv=1.723837665e+09
Aug 16 15:48:35 hostname alloy[357803]: ts=2024-08-16T19:48:35.615562799Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.002529800748814828 upperBound=1.3
Aug 16 15:48:45 hostname alloy[357803]: 2024/08/16 15:48:45 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.getRRW.func2.1 (mux.go:114)
Aug 16 15:48:45 hostname alloy[357803]: ts=2024-08-16T19:48:45.499125328Z level=debug msg="Scrape failed" component_path=/remotecfg component_id=prometheus.scrape.unix_exporter scrape_pool=remotecfg/prometheus.scrape.unix_exporter target=http://alloy.internal:12345/api/v0/component/remotecfg/prometheus.exporter.unix.default/metrics err="server returned HTTP status 400 Bad Request"
Aug 16 15:48:45 hostname alloy[357803]: ts=2024-08-16T19:48:45.615531906Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.16057413836800002 dataOutRate=0.07571767296000001 dataKeptRatio=1 dataPendingRate=0.08485646540800001 dataPending=9.634448302080001 dataOutDuration=0.002529800748814828 timePerSample=0.033410968006785766 desiredShards=0.02145974959892176 highestSent=1.723837665e+09 highestRecv=1.723837725e+09
Aug 16 15:48:45 hostname alloy[357803]: ts=2024-08-16T19:48:45.615560078Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.02145974959892176 upperBound=1.3
Aug 16 15:48:45 hostname alloy[357803]: ts=2024-08-16T19:48:45.961432111Z level=debug msg="runShard timer ticked, sending buffered data" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push samples=5 exemplars=0 shard=0 histograms=0
Aug 16 15:48:55 hostname alloy[357803]: ts=2024-08-16T19:48:55.615099423Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.12845931069440003 dataOutRate=0.16057413836800002 dataKeptRatio=1 dataPendingRate=-0.032114827673599994 dataPending=0 dataOutDuration=0.005161029519051863 timePerSample=0.03214110050040522 desiredShards=0.004128823615241491 highestSent=1.723837725e+09 highestRecv=1.723837725e+09
Aug 16 15:48:55 hostname alloy[357803]: ts=2024-08-16T19:48:55.615221059Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.004128823615241491 upperBound=1.3
Aug 16 15:49:00 hostname alloy[357803]: ts=2024-08-16T19:49:00.499662746Z level=debug msg="Watcher is reading the WAL due to timeout, haven't received any write notifications recently" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push timeout=15s
Aug 16 15:49:05 hostname alloy[357803]: ts=2024-08-16T19:49:05.614534875Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.10276744855552003 dataOutRate=0.12845931069440003 dataKeptRatio=1 dataPendingRate=-0.02569186213888 dataPending=0 dataOutDuration=0.00412882361524149 timePerSample=0.032141100500405216 desiredShards=0.003303058892193192 highestSent=1.723837725e+09 highestRecv=1.723837725e+09
Aug 16 15:49:05 hostname alloy[357803]: ts=2024-08-16T19:49:05.614662012Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.003303058892193192 upperBound=1.3
Aug 16 15:49:15 hostname alloy[357803]: ts=2024-08-16T19:49:15.615394377Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.08221395884441603 dataOutRate=0.10276744855552003 dataKeptRatio=1 dataPendingRate=-0.020553489711104003 dataPending=0 dataOutDuration=0.0033030588921931924 timePerSample=0.032141100500405216 desiredShards=0.002642447113754554 highestSent=1.723837725e+09 highestRecv=1.723837725e+09
Aug 16 15:49:15 hostname alloy[357803]: ts=2024-08-16T19:49:15.615434878Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.002642447113754554 upperBound=1.3
Aug 16 15:49:25 hostname alloy[357803]: ts=2024-08-16T19:49:25.614982883Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.08221395884441603 dataOutRate=0.08221395884441603 dataKeptRatio=1 dataPendingRate=0 dataPending=0 dataOutDuration=0.0026424471137545535 timePerSample=0.032141100500405216 desiredShards=0.002642447113754554 highestSent=1.723837725e+09 highestRecv=1.723837725e+09
Aug 16 15:49:35 hostname alloy[357803]: ts=2024-08-16T19:49:35.615431205Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.05261693366042626 dataOutRate=0.06577116707553282 dataKeptRatio=1 dataPendingRate=-0.013154233415106562 dataPending=0 dataOutDuration=0.002113957691003643 timePerSample=0.032141100500405216 desiredShards=0.0016911661528029144 highestSent=1.723837725e+09 highestRecv=1.723837725e+09
Aug 16 15:49:35 hostname alloy[357803]: ts=2024-08-16T19:49:35.615556617Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.0016911661528029144 upperBound=1.3
Aug 16 15:49:45 hostname alloy[357803]: 2024/08/16 15:49:45 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.getRRW.func2.1 (mux.go:114)
Aug 16 15:49:45 hostname alloy[357803]: ts=2024-08-16T19:49:45.499182207Z level=debug msg="Scrape failed" component_path=/remotecfg component_id=prometheus.scrape.unix_exporter scrape_pool=remotecfg/prometheus.scrape.unix_exporter target=http://alloy.internal:12345/api/v0/component/remotecfg/prometheus.exporter.unix.default/metrics err="server returned HTTP status 400 Bad Request"
Aug 16 15:49:45 hostname alloy[357803]: ts=2024-08-16T19:49:45.615424782Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.14209354692834103 dataOutRate=0.05261693366042626 dataKeptRatio=1 dataPendingRate=0.08947661326791477 dataPending=8.525612815700462 dataOutDuration=0.0016911661528029144 timePerSample=0.032141100500405216 desiredShards=0.018268171889131414 highestSent=1.723837725e+09 highestRecv=1.723837785e+09
Aug 16 15:49:45 hostname alloy[357803]: ts=2024-08-16T19:49:45.6154549Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.018268171889131414 upperBound=1.3
Aug 16 15:49:46 hostname alloy[357803]: ts=2024-08-16T19:49:46.124050724Z level=debug msg="runShard timer ticked, sending buffered data" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push samples=5 exemplars=0 shard=0 histograms=0
Aug 16 15:49:55 hostname alloy[357803]: ts=2024-08-16T19:49:55.615445722Z level=debug msg=QueueManager.calculateDesiredShards component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push dataInRate=0.11367483754267282 dataOutRate=0.14209354692834103 dataKeptRatio=1 dataPendingRate=-0.028418709385668206 dataPending=0 dataOutDuration=0.004278142522242332 timePerSample=0.030107929703520143 desiredShards=0.003422514017793866 highestSent=1.723837785e+09 highestRecv=1.723837785e+09
Aug 16 15:49:55 hostname alloy[357803]: ts=2024-08-16T19:49:55.615475163Z level=debug msg=QueueManager.updateShardsLoop component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push lowerBound=0.7 desiredShards=0.003422514017793866 upperBound=1.3
Aug 16 15:50:00 hostname alloy[357803]: ts=2024-08-16T19:50:00.499766975Z level=debug msg="Watcher is reading the WAL due to timeout, haven't received any write notifications recently" component_path=/remotecfg component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=eff791 url=https://mimir..domain/api/v1/push timeout=15s
```
```

### PR DESCRIPTION
**Pull request by tpaschalis**
#### PR Description

At some point during #1372 I accidentally changed the pathPrefix used for the lookup of remotecfg components, stripping out the `remotecfg/` prefix and failing the component lookups.

After this change, I've verified that both local and remotecfg component lookups work as intended in parallel, both through the default and the in-memory listener 

```
$ curl -i localhost:12349/api/v0/component/remotecfg/self.default/prometheus.exporter.self.default/metrics
HTTP/1.1 200 OK
Content-Type: text/plain; version=0.0.4; charset=utf-8; escaping=values
Date: Mon, 19 Aug 2024 15:43:54 GMT
Transfer-Encoding: chunked

# HELP alloy_build_info A metric with a constant '1' value labeled by version, revision, branch, goversion from which alloy was built, and the goos and goarch for the build.
# TYPE alloy_build_info gauge

$  curl -i localhost:12349/api/v0/component/prometheus.exporter.self.default/metrics
HTTP/1.1 200 OK
Content-Type: text/plain; version=0.0.4; charset=utf-8; escaping=values
Date: Mon, 19 Aug 2024 15:41:48 GMT
Transfer-Encoding: chunked

# HELP alloy_build_info A metric with a constant '1' value labeled by version, revision, branch, goversion from which alloy was built, and the goos and goarch for the build.
# TYPE alloy_build_info gauge
```

#### Which issue(s) this PR fixes
Fixes #1486 

#### PR Checklist

- [ ] CHANGELOG.md updated (N/A) 
- [ ] Documentation added (N/A)
- [ ] Tests updated 
- [ ] Config converters updated (N/A)

### CODE REVIEW

File: internal/service/http/http.go [hunk 1]
```diff
@@ -178,8 +178,9 @@ func (s *Service) Run(ctx context.Context, host service.Host) error {
 	}
 
 	// NOTE(@tpaschalis) These need to be kept in order for the longer
-	// remotecfg prefix to be invoked correctly.
-	r.PathPrefix(s.componentHttpPathPrefixRemotecfg).Handler(s.componentHandler(remoteCfgHostProvider(host), s.componentHttpPathPrefixRemotecfg))
+	// remotecfg prefix to be invoked correctly. The pathPrefix is still the
+	// same so that `remotecfg/` is not stripped from component lookups.
+	r.PathPrefix(s.componentHttpPathPrefixRemotecfg).Handler(s.componentHandler(remoteCfgHostProvider(host), s.componentHttpPathPrefix))
```
Comment (thampiotr) [inline internal/service/http/http.go:183]: if both calls to `s.componentHandler` set pathPrefix to the same value, we should probably not have it as a method parameter

**Review by thampiotr — APPROVED** [review]
One comment, but LGTM otherwise

File: internal/service/http/http.go (hunk 1 above)
Comment (tpaschalis) [reply internal/service/http/http.go:183]: I think you're right. Do you mind if I follow up on this in a different PR? The parameter was already there so I want to see if there are any other potential uses for it.

Comment (thampiotr) [reply internal/service/http/http.go:183]: I don't really mind, although it should be quite easy to check cause it'd give you compilation error.
