### PR TITLE
Fix handling of multiplexed long lines in Docker logs

### LINKED ISSUE #4625: `loki.source.docker` corrupts logs split by docker
### Component(s)

loki.source.docker

### What's wrong?

Here is an example of this:
```json
{
    "a": 1033461950,
    "b": true
},
2025-10-17T22: 40: 09.574025386Z {
    "a": 1033471950,
    "b": true
},
{
    "a": 1034411950,
    "b": true
},
```

### Steps to reproduce

1.Set up docker JSON logging with alloy and loki.
2.Log something that exceeds the docker line limit and will be split.

### System information

_No response_

### Software version

Grafana Alloy v1.11.2

### Configuration

```text
discovery.docker "container_logs" {
	host             = "unix:///var/run/docker.sock"
	refresh_interval = "10s"

	filter {
		name   = "label"
		values = ["logging=alloy"]
	}
}

discovery.relabel "container_logs" {
	targets = discovery.docker.container_logs.targets

	rule {
		source_labels = ["__meta_docker_container_id"]
		target_label  = "container_id"
	}
}

loki.source.docker "container_logs" {
	host       = "unix:///var/run/docker.sock"
	targets    = discovery.relabel.container_logs.output
	forward_to = [loki.process.container_logs.receiver]
	refresh_interval = "10s"
}

loki.process "container_logs" {
	forward_to = [loki.write.default.receiver]
}

loki.write "default" {
	endpoint {
		url = "http://loki:3100/loki/api/v1/push"
	}
	external_labels = {}
}
```

### Logs

```text

```

### Tip

<sub>React with 👍 if this issue is important to you.</sub>

### PR DESCRIPTION
**Pull request by axd1x8a**
#### PR Description
By default, Docker splits lines over 16KB into multiple frames. `stdcopy.StdCopy` handles multiplexing itself, but not inserted timestamps, which corrupts logs:
```json
{
    "a": 1033461950,
    "b": true
},
2025-10-17T22: 40: 09.574025386Z {
    "a": 1033471950,
    "b": true
},
{
    "a": 1034411950,
    "b": true
},
```
This PR adds a wrapper for `stdcopy.StdCopy` streams that checks if incoming streams are part of a larger log line and concatenates them into one, removing timestamp in the process.

Additionally, functions for reading streams and parsing timestamps were changed to operate on bytes to avoid allocations.
#### Which issue(s) this PR fixes
#4625
#1881

#### Notes to the Reviewer
Not sure about the policy on unsafe code here, but the usage of `unsafe.String` in `extractTsFromBytes` makes sense because we know that the bytes won't be modified and it gives just a little bit more performance from my testing.

#### PR Checklist

- [x] CHANGELOG.md updated
- [x] Tests updated

### CODE REVIEW

File: internal/component/loki/source/docker/internal/dockertarget/target.go [hunk 1]
```diff
@@ -321,3 +313,68 @@ func (t *Target) getStreamLabels(logStream string) model.LabelSet {
...
+	logger      log.Logger
+	buffer      *bytes.Buffer
+	isBuffering bool
+}
+
+var bufferPool = sync.Pool{
+	New: func() interface{} {
+		buf := &bytes.Buffer{}
+		buf.Grow(dockerMaxChunkSize * 2)
+		return buf
```
Comment (dehaansa) [inline internal/component/loki/source/docker/internal/dockertarget/target.go]: May as well initialize with that size instead of Growing.

```suggestion
	return bytes.NewBuffer(make([]byte, 0, dockerMaxChunkSize * 2))
```

**Comment by axd1x8a** [comment]
I will check why tests fail and fix it later

**Comment by axd1x8a** [comment]
Please let me know if PR needs to be rebased to keep up with the main branch. I don't want to run your CI runners unnecessarily

File: internal/component/loki/source/docker/internal/dockertarget/target.go [hunk 2]
```diff
@@ -128,53 +136,33 @@ func (t *Target) processLoop(ctx context.Context, tty bool, reader io.ReadCloser
...
-	)
-
-	for isPrefix && err == nil {
-		line, isPrefix, err = r.ReadLine()
-		ln = append(ln, line...)
+		return time.Time{}, nil, fmt.Errorf("could not parse timestamp: %w", err)
 	}
-
-	return string(ln), err
+	return ts, line[spaceIdx+1:], nil
```
Comment (dehaansa) [inline internal/component/loki/source/docker/internal/dockertarget/target.go:157]: This seems more fragile than the previous behavior using strings.SplitN. If, for example, the whole log is "TS " then spaceIdx is the last valid index, and this can panic. I understand that _shouldn't_ happen, but I would rather have the more flexible code that is safer. bytes.SplitN exists, so I think we should just use it.

File: internal/component/loki/source/docker/internal/dockertarget/target.go [hunk 3]
```diff
@@ -34,6 +36,7 @@ const (
 	dockerLabel                = model.MetaLabelPrefix + "docker_"
 	dockerLabelContainerPrefix = dockerLabel + "container_"
 	dockerLabelLogStream       = dockerLabelContainerPrefix + "log_stream"
+	dockerMaxChunkSize         = 16384
```
Comment (dehaansa) [inline internal/component/loki/source/docker/internal/dockertarget/target.go:39]: Is there any need to have this configurable?

File: internal/component/loki/source/docker/internal/dockertarget/target.go [hunk 4]
```diff
@@ -128,53 +136,33 @@ func (t *Target) processLoop(ctx context.Context, tty bool, reader io.ReadCloser
...
+func extractTsFromBytes(line []byte) (time.Time, []byte, error) {
+	const timestampLayout = "2006-01-02T15:04:05.999999999Z07:00"
+
+	spaceIdx := bytes.IndexByte(line, ' ')
+	if spaceIdx == -1 {
+		return time.Time{}, nil, fmt.Errorf("could not find timestamp in bytes")
 	}
-	ts, err := time.Parse("2006-01-02T15:04:05.999999999Z07:00", pair[0])
+	// We know that the bytes won't be modified during the time.Parse call, so it's safe to use unsafe.String here
+	ts, err := time.Parse(timestampLayout, unsafe.String(&line[0], spaceIdx))
```
Comment (dehaansa) [inline internal/component/loki/source/docker/internal/dockertarget/target.go:153]: I don't see a single other use of unsafe.String in the codebase. If the performance benefit was significant I'm open to it, otherwise I'd rather leave it out.

**Review by dehaansa — COMMENTED** [review]
Apologies that the review here has been slow! Thanks for this contribution, have a few comments to resolve.

File: internal/component/loki/source/docker/internal/dockertarget/target.go (hunk 4 above)
Comment (axd1x8a) [reply internal/component/loki/source/docker/internal/dockertarget/target.go:153]: These are the results I got when I benchmarked `string(line[:spaceIdx])` and the current solution
```
cpu: AMD Ryzen 9 7900X 12-Core Processor
                                                     │ without_unsafe.txt │           with_unsafe.txt           │
                                                     │       sec/op       │   sec/op     vs base                │
ExtractTsFromBytes/ShortLines_10k-24                 351.8µ ±  7%   331.7µ ± 1%   -5.69% (p=0.000 n=10)
ExtractTsFromBytes/MediumLines_1k-24                 38.29µ ±  3%   32.81µ ± 0%  -14.32% (p=0.000 n=10)
ExtractTsFromBytes/LongLines_100-24                  4.016µ ±  8%   3.280µ ± 0%  -18.33% (p=0.000 n=10)
ExtractTsFromBytes/VeryLongLines_50-24               2.036µ ± 10%   1.649µ ± 1%  -19.03% (p=0.000 n=10)
ExtractTsFromBytes/MixedWorkload-24                  441.7µ ±  1%   369.0µ ± 0%  -16.45% (p=0.000 n=10)
ExtractTsFromBytes/Parallel_MixedWorkload-24         34.44µ ±  2%   32.14µ ± 2%   -6.66% (p=0.000 n=10)
geomean                                                      34.46µ         29.78µ       -13.58%

                                                     │ without_unsafe.txt │           with_unsafe.txt           │
                                                     │        B/op        │    B/op     vs base                 │
ExtractTsFromBytes/ShortLines_10k-24                 0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
ExtractTsFromBytes/MediumLines_1k-24                 0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
ExtractTsFromBytes/LongLines_100-24                  0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
ExtractTsFromBytes/VeryLongLines_50-24               0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
ExtractTsFromBytes/MixedWorkload-24                  0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
ExtractTsFromBytes/Parallel_MixedWorkload-24         0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
geomean                                                                 ²               +0.00%                ²
¹ all samples are equal
² summaries must be >0 to compute geomean

                                                     │ without_unsafe.txt │           with_unsafe.txt           │
                                                     │     allocs/op      │ allocs/op   vs base                 │
ExtractTsFromBytes/ShortLines_10k-24                 0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
ExtractTsFromBytes/MediumLines_1k-24                 0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
ExtractTsFromBytes/LongLines_100-24                  0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
ExtractTsFromBytes/VeryLongLines_50-24               0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
ExtractTsFromBytes/MixedWorkload-24                  0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
ExtractTsFromBytes/Parallel_MixedWorkload-24         0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
geomean                                                                 ²               +0.00%                ²
¹ all samples are equal
² summaries must be >0 to compute geomean
```

```
              lines line size   total data
ShortLines    10000 ~100 bytes  ~1 MB
MediumLines   1000  ~2 KB       ~2 MB
LongLines     100   ~50 KB      ~5 MB
VeryLongLines 50    ~500 KB     ~25 MB
MixedWorkload 11150	mixed       ~33 MB
```

File: internal/component/loki/source/docker/internal/dockertarget/target.go (hunk 2 above)
Comment (axd1x8a) [reply internal/component/loki/source/docker/internal/dockertarget/target.go:157]: I think it's better to add an if statement `spaceIdx == -1 || spaceIdx >= len(line)-1`. This is because `bytes.SplitN` will allocate a slice, and compared to the `unsafe.String`vs`string` case, this will lead to a significant performance regression
```
                                             │ with_unsafe.txt │           bytes_split.txt            │
                                             │     sec/op      │   sec/op     vs base                 │
ExtractTsFromBytes/ShortLines_10k-24               329.6µ ± 0%   536.7µ ± 2%   +62.85% (p=0.000 n=10)
ExtractTsFromBytes/MediumLines_1k-24               32.78µ ± 0%   51.73µ ± 2%   +57.80% (p=0.000 n=10)
ExtractTsFromBytes/LongLines_100-24                3.286µ ± 0%   5.189µ ± 2%   +57.94% (p=0.000 n=10)
ExtractTsFromBytes/VeryLongLines_50-24             1.646µ ± 1%   2.629µ ± 1%   +59.74% (p=0.000 n=10)
ExtractTsFromBytes/MixedWorkload-24                368.1µ ± 0%   598.2µ ± 4%   +62.51% (p=0.000 n=10)
ExtractTsFromBytes/Parallel_MixedWorkload-24       32.01µ ± 0%   86.20µ ± 2%  +169.32% (p=0.000 n=10)
geomean                                            29.71µ        51.89µ        +74.65%

                                             │ with_unsafe.txt │        bytes_split.txt         │
                                             │      B/op       │     B/op      vs base          │
ExtractTsFromBytes/ShortLines_10k-24              0.0Ki ± 0%     468.8Ki ± 0%  ? (p=0.000 n=10)
ExtractTsFromBytes/MediumLines_1k-24             0.00Ki ± 0%     46.88Ki ± 0%  ? (p=0.000 n=10)
ExtractTsFromBytes/LongLines_100-24             0.000Ki ± 0%     4.688Ki ± 0%  ? (p=0.000 n=10)
ExtractTsFromBytes/VeryLongLines_50-24          0.000Ki ± 0%     2.344Ki ± 0%  ? (p=0.000 n=10)
ExtractTsFromBytes/MixedWorkload-24               0.0Ki ± 0%     522.7Ki ± 0%  ? (p=0.000 n=10)
ExtractTsFromBytes/Parallel_MixedWorkload-24      0.0Ki ± 0%     522.7Ki ± 0%  ? (p=0.000 n=10)
geomean                                                      ¹   63.56Ki       ?
¹ summaries must be >0 to compute geomean

                                             │ with_unsafe.txt │        bytes_split.txt        │
                                             │    allocs/op    │  allocs/op   vs base          │
ExtractTsFromBytes/ShortLines_10k-24              0.00k ± 0%     10.00k ± 0%  ? (p=0.000 n=10)
ExtractTsFromBytes/MediumLines_1k-24             0.000k ± 0%     1.000k ± 0%  ? (p=0.000 n=10)
ExtractTsFromBytes/LongLines_100-24                 0.0 ± 0%      100.0 ± 0%  ? (p=0.000 n=10)
ExtractTsFromBytes/VeryLongLines_50-24             0.00 ± 0%      50.00 ± 0%  ? (p=0.000 n=10)
ExtractTsFromBytes/MixedWorkload-24               0.00k ± 0%     11.15k ± 0%  ? (p=0.000 n=10)
ExtractTsFromBytes/Parallel_MixedWorkload-24      0.00k ± 0%     11.15k ± 0%  ? (p=0.000 n=10)
geomean                                                      ¹   1.356k       ?
¹ summaries must be >0 to compute geomean
```

File: internal/component/loki/source/docker/internal/dockertarget/target.go (hunk 3 above)
Comment (axd1x8a) [reply internal/component/loki/source/docker/internal/dockertarget/target.go:39]: I think it's better to have a constant with a self-describing name than a magic number in the code

File: internal/component/loki/source/docker/internal/dockertarget/target.go (hunk 2 above)
Comment (dehaansa) [reply internal/component/loki/source/docker/internal/dockertarget/target.go:157]: Sounds good. 👍

File: internal/component/loki/source/docker/internal/dockertarget/target.go (hunk 4 above)
Comment (dehaansa) [reply internal/component/loki/source/docker/internal/dockertarget/target.go:153]: Sure, that seems worthwhile. 👍

File: internal/component/loki/source/docker/internal/dockertarget/target.go (hunk 3 above)
Comment (dehaansa) [reply internal/component/loki/source/docker/internal/dockertarget/target.go:39]: Sorry if I phrased that poorly - I was actually trying to understand if you think this should be user overrideable for any reason.

File: CHANGELOG.md [hunk 5]
```diff
@@ -138,6 +138,8 @@ v1.12.0-rc.0
 
 ### Bugfixes
 
+- Fix Docker log corruption for multiplexed long lines. (@axd1x8a)
```
Comment (dehaansa) [inline CHANGELOG.md]: Changelog likely needs to be manually updated from main to hit the unreleased section.

Comment (axd1x8a) [reply CHANGELOG.md]: I can rebase to main and also move this line up to the unreleased section if needed

File: internal/component/loki/source/docker/internal/dockertarget/target.go (hunk 3 above)
Comment (axd1x8a) [reply internal/component/loki/source/docker/internal/dockertarget/target.go:39]: Well, I don't think Docker will ever change this. When I searched for the original solution, I found that their answer to one of the issues was for the consumer libraries to adapt to this instead of changing the limit on Docker's side. So, yeah, I don't see the need for a configuration here

**Review by dehaansa — APPROVED** [review]
Once you rebase to main and CI is happy we can get this merged. Thanks for your patience.
