### PR TITLE
Fix modulecontroller handling in foreach

### LINKED ISSUE #3366: foreach: UI compatibility
Given the following config, the View button does not work for the templated components

```
foreach {
    collection = [{"name"="test", "cmdline"=["test"]}, {"name"="test2", "cmdline"=["test2"]}]
    var = "each"

    template {
        prometheus.exporter.process "default" {
            matcher {
                name = each["name"]
                cmdline = each["cmdline"]
            }
        }
    }
}
```

Image

The View button does work when wrapping `foreach` in a declare

```
declare "test_component" {
    argument "test_map_arg" { }

    foreach {
        collection = argument.test_map_arg.value
        var = "each"

        template {
            prometheus.exporter.process "default" {
                matcher {
                    name = each["name"]
                    cmdline = each["cmdline"]
                }
            }
        }
    }
}

test_component "test" {
    test_map_arg = [{"name"="test", "cmdline"=["test"]}, {"name"="test2", "cmdline"=["test2"]}]
}
```

Additionally, the `Module components` section disappears from the UI when a Dependencies section is included with the following config

```
declare "test_component" {
    argument "test_map_arg" { }

    foreach {
        collection = argument.test_map_arg.value
        var = "each"

        template {
            prometheus.exporter.process "default" {
                matcher {
                    name = each["name"]
                    cmdline = each["cmdline"]
                }
            }

            prometheus.scrape "default" {
                targets    = prometheus.exporter.process.default.targets
                forward_to = [prometheus.remote_write.default.receiver]
            }
        }
    }

    prometheus.remote_write "default" {
        endpoint {
            url = "REDACTED"
            basic_auth {
                username = "REDACTED"
                password = "REDACTED"
            }
        }
    }
}

test_component "test" {
    test_map_arg = [{"name"="test", "cmdline"=["test"]}, {"name"="test2", "cmdline"=["test2"]}]
}
```

Image

### PR DESCRIPTION
**Pull request by wildum**
#### PR Description

The module controller was recreated on every evaluation of the foreach block. The problem is that the foreach custom component children register only once at creation to the current module controller. As a result, the components that were not registered to the latest module controller were not available in the UI.

The fix in this PR is to only recreate the module controller when the enable_metrics param is toggled and when that happens all custom component children are stopped so that they can be recreated by the new module controller. This overhead should be acceptable because this parameter should not be toggled very often.

#### Which issue(s) this PR fixes

Fixes #3366

#### PR Checklist

- [x] CHANGELOG.md updated
- [na] Documentation added
- [x] Tests updated
- [na] Config converters updated

### CODE REVIEW

**Review by kalleep — APPROVED** [review]
LGTM

File: internal/runtime/internal/controller/node_config_foreach.go [hunk 1]
```diff
@@ -61,6 +61,9 @@ type ForeachConfigNode struct {
 
 	dataFlowEdgeMut  sync.RWMutex
 	dataFlowEdgeRefs []string
+
+	metricsEnabled bool
```
Comment (kalleep) [inline internal/runtime/internal/controller/node_config_foreach.go:65]: nit: I don't think you need track this because we kinda already do it with `fn.moduleControllerOpts.RegOverride`.
```
else if fn.metricsEnabled && fn.moduleControllerOpts.RegOverride != nil && fn.runner != nil
```

Comment (wildum) [reply internal/runtime/internal/controller/node_config_foreach.go]: good catch, I actually simplified it even further, lmk if that's ok

Comment (kalleep) [reply internal/runtime/internal/controller/node_config_foreach.go]: Yeah that is better!
